### ISSUE TITLE
Add a travis configuration.

### ISSUE THREAD

**Issue by hobbestigrou** [boblefrag/python-rest-api-framework#12]
I think it is interesting to add a travis configuration to execute the tests
and have test integration continues:

```
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"

install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
script: nosetests --nologcapture --all-modules tests
notifications:
  irc:
    - "irc.freenode.org#boblefrag"
  on_success: change
  on_failure: always
  template:
      - "[%{build_number}] %{message} (%{build_url})"
```

Like that. It's can be cool.
